List<String> getLyrics() {
  return [
    'D-Note Is On The Beat',
    'The Beatllionare',
    'Justin, Justin, Justin, Justin',
    'Justin, Justin, Justin, Justin, Justin',
    '¡Esto es Arcángel: "La Maravilla"!',
    'Salimo\' de abajo endecando el trabajo',
    'El paquete sin un tajo, el dinero lo bajo',
    'Y el que nos venga a frontear, se lo va a llevar el que lo trajo',
    'Le damo\' en la mother',
    'Paso el tiempo, tengo dinero, respeto y poder',
    'Y este 2022 venimo\' a romperla peor en el nombre del brother, yeah',
    'Cabrón, ¿tú no ve\'?',
    'Me tuve que joder con cojone\' pa\' que to\'a esta mierda se dé',
    'Valoro más el tiempo desde que vi lo que cuesta un Patek',
    'No es lo mismo cuando me levanto desde que Justin se me fue',
    'Pero en el nombre tuyo la vamo\' a romper como e\'',
    'Cabrón, ¿tú no ve\'?',
    'Me tuve que joder con cojone\' pa\' que to\'a esta mierda se dé',
    'Valoro más el tiempo desde que vi lo que cuesta un Patek',
    'No es lo mismo cuando me levanto desde que Justin se me fue',
    'Pero en el nombre tuyo la vamo\' a romper como e\'',
    'Dinero encima, mucha envidia encima, por eso la cargo encima',
    'Plomo no escatima, y al primero que se nos pare al frente le pasamo\' po\' encima',
    'El nombre de Justin no muere en La Calma Suite, sí, esa es mi esquina',
    'Diagnosticaron que soy algo letal, una mezcla del COVID con gripe porcina (¡wuh!)',
    'Mamabicho, el nombre mío pesa y suena por el mundo entero',
    'Empresario, millonario, tutor y rapero',
    'Yo sigo vigente porque no corro con desespero',
    'Y mis hijos siguen rico\' si algún día me muero',
    'No soy Ángelo y me dicen: "el bo"',
    'Por encima de mí, Dios, por encima \'e ustede\', yo, nigga',
    'Quieren tumbarme, pero e\' que están fallando en el intento',
    'Y quieren contratarme, pero si no hay más de dosciento\'',
    'Sorry, pero no hay evento, ay',
    'Cabrón, ¿tú no ve\'?',
    'Me tuve que joder con cojone\' pa\' que to\'a esta mierda se dé',
    'Valoro más el tiempo desde que vi lo que cuesta un Patek',
    'No es lo mismo cuando me levanto desde que Justin se me fue',
    'Pero en el nombre tuyo la vamo\' a romper como e\'',
    'Cabrón, ¿tú no ve\'?',
    'Me tuve que joder con cojone\' pa\' que to\'a esta mierda se dé',
    'Valoro más el tiempo desde que vi lo que cuesta un Patek',
    'No es lo mismo cuando me levanto desde que Justin se me fue',
    'Pero en el nombre tuyo la vamo\' a romper como e\' (ejem, ey, yo)',
    'Yo no brego con maleante\' de rede\' (no)',
    'Las bala\' del palo traspasan parede\' (prr)',
    'Cabrón, tu ganga es más paquetera que FedEx (ah)',
    'Y yo sin estar pega\'o cobro más que ustedes (¡wuh!)',
    'Cada paso que tomo Justin lo respalda (yes)',
    'Aunque no sea lo mismo cada vez que salga (pero)',
    'Pero Dios me guarda, él vela mi espalda',
    'La familia ready, las cuentas salda\', nigga (let\'s go)',
    '¿Tú no ve\' el respeto que yo tengo? (tengo)',
    'Parezco kilero y yo ni vendo (uh)',
    'Triste, pero yo sigo fluyendo',
    'Porque no tengo el brother a mi la\'o cuando prendo (¡auh!, damn)',
    'Cabrón, ¿tú no ve\'?',
    'Me tuve que joder con cojone\' pa\' que to\'a esta mierda se dé',
    'Valoro más el tiempo desde que vi lo que cuesta un Patek',
    'No es lo mismo cuando me levanto desde que Justin se me fue',
    'Pero en el nombre tuyo la vamo\' a romper como e\'',
    'Cabrón, ¿tú no ve\'?',
    'Me tuve que joder con cojone\' pa\' que to\'a esta mierda se dé',
    'Valoro más el tiempo desde que vi lo que cuesta un Patek',
    'No es lo mismo cuando me levanto desde que Justin se me fue',
    'Pero en el nombre tuyo la vamo\' a romper como e\'',
    'Justin, Justin, Justin, Justin',
    'Justin, Justin, Justin, Justin, Justin'
  ];

}